// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqL6T9G1NaTdsfA8fAVaS3AH5HrZptBOA',
    appId: '1:1013170566217:web:c0105ba89ea604b4ddbb98',
    messagingSenderId: '1013170566217',
    projectId: 'flutter-firebase-auth-14b22',
    authDomain: 'flutter-firebase-auth-14b22.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-14b22.firebasestorage.app',
    measurementId: 'G-MD17SMT8LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44UndioOBcDdWlwOejvtyX1DE6bi64Iw',
    appId: '1:1013170566217:android:e2399deec329ec42ddbb98',
    messagingSenderId: '1013170566217',
    projectId: 'flutter-firebase-auth-14b22',
    storageBucket: 'flutter-firebase-auth-14b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5eNMUEIwiKr1pmwBPl3FUtgV5pAPNdg',
    appId: '1:1013170566217:ios:1cdac6209ec1ddf5ddbb98',
    messagingSenderId: '1013170566217',
    projectId: 'flutter-firebase-auth-14b22',
    storageBucket: 'flutter-firebase-auth-14b22.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu5eNMUEIwiKr1pmwBPl3FUtgV5pAPNdg',
    appId: '1:1013170566217:ios:1cdac6209ec1ddf5ddbb98',
    messagingSenderId: '1013170566217',
    projectId: 'flutter-firebase-auth-14b22',
    storageBucket: 'flutter-firebase-auth-14b22.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqL6T9G1NaTdsfA8fAVaS3AH5HrZptBOA',
    appId: '1:1013170566217:web:f56ed77b07090403ddbb98',
    messagingSenderId: '1013170566217',
    projectId: 'flutter-firebase-auth-14b22',
    authDomain: 'flutter-firebase-auth-14b22.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-14b22.firebasestorage.app',
    measurementId: 'G-58J2YPCPMS',
  );
}
